on:
  push:
    branches:
      - main
name: 🚀 Deploy Application on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ftp.cloud209.cloudwebhosting.com
        username: lionel@clskycompany.com
        password: YjtFS*d%AWC&
        server-dir: ../mobile.clskycompany.com/
